language: erlang
otp_release:
  - 18.3
  - 19.1
install:
  - make
  - ./rebar3 update
script:
  - make test
  - make dialyzer
sudo: required
dist: trusty
branches:
  except:
    - metrics
    - benchmarks
notifications:
  webhooks: https://discordapp.com/api/webhooks/290937576586739712/xW2LspB3uglPkmrX5EXQrt-sszimngua5hmwt3UsmWSnNME-i1IZh4znqw2ri9VjKVMw
